
import React, { useState } from 'react';
import { DistrictALDPI } from '../types';
import { GoogleGenAI, Type } from "@google/genai";
import { simulateRecovery } from '../services/aldpiEngine';

export const PolicyAutopilot: React.FC<{ district: DistrictALDPI }> = ({ district }) => {
  const [resources, setResources] = useState(0);
  const [loading, setLoading] = useState(false);
  const [recommendation, setRecommendation] = useState<{ brief: string, justification: string, provenance: string } | null>(null);

  const simulatedLfi = simulateRecovery(district.lfi, resources);

  const generateAIPolicy = async () => {
    setLoading(true);
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    try {
      const response = await ai.models.generateContent({
        model: 'gemini-3-flash-preview',
        contents: `Analyze District: ${district.name}. 
          Current LFI: ${district.lfi}. 
          Metrics: ${JSON.stringify(district.metrics)}. 
          Simulated Resource Increase: ${resources} mobile vans.
          Provide an executive policy recommendation for UIDAI Regional Office.
          Include a clear justification for why this action is chosen and a provenance note describing the logic (LFI decay simulation).`,
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              brief: { type: Type.STRING },
              justification: { type: Type.STRING },
              provenance: { type: Type.STRING }
            },
            required: ["brief", "justification", "provenance"]
          }
        }
      });
      const data = JSON.parse(response.text);
      setRecommendation(data);
    } catch (e) {
      setRecommendation({
        brief: "Immediate deployment of mobile kits suggested.",
        justification: "Friction exceeds thresholds in localized blocks.",
        provenance: "Model: Fallback Logic; Data: Regional LFI."
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="bg-slate-900 text-white rounded-2xl p-6 shadow-2xl border border-slate-700">
      <div className="flex items-center gap-2 mb-4">
        <div className="w-2 h-2 rounded-full bg-blue-500 animate-pulse"></div>
        <h3 className="font-bold text-sm uppercase tracking-wider">Policy Autopilot (Sim)</h3>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        <div className="space-y-4">
          <label className="block text-[10px] text-slate-400 font-bold uppercase">Resource Allocation (Mobile Kits)</label>
          <input 
            type="range" min="0" max="10" value={resources} 
            onChange={(e) => setResources(parseInt(e.target.value))}
            className="w-full h-2 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-blue-500"
          />
          <div className="flex justify-between text-[10px] font-mono text-slate-500">
            <span>Current Status</span>
            <span>+{resources} Units</span>
          </div>

          <div className="p-4 bg-slate-800/50 rounded-xl border border-slate-700">
            <p className="text-[10px] text-slate-400 uppercase mb-2">Projected Impact</p>
            <div className="flex items-end gap-2">
              <span className="text-2xl font-black text-blue-400">{simulatedLfi.toFixed(2)}</span>
              <span className="text-xs text-slate-500 pb-1">LFI (New Score)</span>
            </div>
            <div className="mt-2 text-[10px] text-emerald-400 font-bold">
              {((district.lfi - simulatedLfi) / district.lfi * 100).toFixed(0)}% Friction Reduction
            </div>
          </div>
        </div>

        <div className="space-y-4">
          <button 
            onClick={generateAIPolicy}
            disabled={loading}
            className="w-full py-3 bg-blue-600 hover:bg-blue-700 rounded-xl font-bold text-xs transition-all shadow-lg shadow-blue-900/40"
          >
            {loading ? 'Synthesizing Policy...' : 'Run Policy Inference'}
          </button>
          
          <p className="text-[9px] text-slate-500 text-center font-medium italic leading-tight">
            All recommendations generated by this system are advisory and require explicit manual approval by a verified UIDAI Principal before execution.
          </p>
          
          <div className="min-h-[140px] p-4 bg-slate-950/50 rounded-xl border border-blue-900/30 text-[11px] text-slate-300 leading-relaxed overflow-y-auto max-h-[250px] custom-scrollbar">
            {recommendation ? (
              <div className="space-y-4">
                <div>
                  <span className="block text-[9px] font-black text-blue-400 uppercase mb-1">Recommendation</span>
                  <p className="font-bold text-white">{recommendation.brief}</p>
                </div>
                <div>
                  <span className="block text-[9px] font-black text-slate-500 uppercase mb-1">Audit Justification</span>
                  <p className="italic text-slate-400">"{recommendation.justification}"</p>
                </div>
                <div>
                  <span className="block text-[9px] font-black text-slate-500 uppercase mb-1">Provenance</span>
                  <p className="text-[9px] font-mono text-slate-500">{recommendation.provenance}</p>
                </div>
              </div>
            ) : (
              <p className="italic text-slate-500 text-center py-8">Adjust resources and run inference to see AI-driven decision support recommendations with audit justification.</p>
            )}
          </div>
        </div>
      </div>
      <div className="mt-6 flex items-center justify-between">
        <div className="flex items-center gap-2 text-[9px] text-slate-500 font-medium">
          <span className="w-1 h-1 bg-slate-500 rounded-full"></span>
          <span>Decision Support System - RTI Compliant Disclosures</span>
        </div>
        <div className="px-2 py-0.5 bg-white/5 rounded text-[8px] font-bold text-slate-500">LEVEL 3 ANONYMIZED</div>
      </div>
    </div>
  );
};
